---
- name: "Manage software"
  tags:
    - software
    - software.pkg
    - software.key
    - software.repo
    - software.info
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family }}.yaml"
    apply:
      tags:
        - software
