---
- name: "Manage software with 'dnf'"
  ansible.builtin.dnf:
    name: "{{ item['name'] }}"
    state: "{{ item['state'] | default(omit, true) }}"
    download_only: "{{ item['download_only'] | default(omit, true) }}"
    download_dir: "{{ item['download_dir'] | default(omit, true) }}"
  loop: "{{ software_pkgs }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  become: true
